### ISSUE TITLE
future request: mqtt

### ISSUE THREAD

**Issue by wutu** [sticilface/Melvanimate#1]
Hi, thanks for https://github.com/sticilface/ESP8266-wifi project. Nice work.
I want to ask whether the new project you count the inclusion MQTT?
It is a unique solution with MQTT for "Neopixel" I know.
Thank you once again.

**Comment by sticilface** [comment]
The answer to your question is yes. 

I'm surprised you noticed this sneaky repository. I've only uploaded it as someone wanted to test it out, with no docu intentionally.  it is far far from complete at the moment. I've kind of bitten off more than I can chew, and it is taking me a long long time to get things to where I'm happy. I'm getting there though! 

Trying at the moment to keep as much out of ram as possible! 

I will keep you posted. 

A

**Comment by wutu** [comment]
Thank you very much for your answer. I look forward to. And good luck.
