### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by jpontius** [sticilface/Melvanimate#12]
I'm just starting out, getting this error after cloning the repository. 

```
stat /tmp/Melvanimate/examples/Melvanimate-example/data/edit.htm.gz: no such file or directory

Error compiling.
```

**Comment by jpontius** [comment]
Looks like edit.htm.gz is a symlink somewhere.

**Comment by sticilface** [comment]
sorry.  I'll tidy the data directory up.  Most of those files don't need to be there.  Good spot!

**Comment by jpontius** [comment]
Super fast.  Thanks!

**Comment by sticilface** [comment]
https://github.com/sticilface/Melvanimate/commit/0691bbbde9431797edc27d9d3d21e96eb325e615
hopefully sorted

**Comment by deennoo** [comment]
Hello,

Installing Lib you advice, get a compil error : 

```
In file included from C:\Users\Nico\Documents\Arduino\libraries\Melvanimate-master\src/EffectManager.h:8:0,
                 from C:\Users\Nico\Documents\Arduino\libraries\Melvanimate-master\src/Melvanimate.h:15,
                 from Melvanimate-example.ino:31:
C:\Users\Nico\Documents\Arduino\libraries\Melvanimate-master\src/palette.h:9:22: fatal error: RgbColor.h: No such file or directory
 #include <RgbColor.h>
                      ^
compilation terminated.
Erreur lors de la compilation.
```

Did you get some idea to help me please ?

**Comment by sticilface** [comment]
That include comes from neopixelbus, do you have that lib installed? 

Might have to tweak the path a little. But I'm not sure.

**Comment by sticilface** [comment]
Get it working? 

I'm going to recommend you do another pull of the lib. 
I've actually commented out that include.  but i'll add it back. neopixelbus moved things into a different folder structure. 

let me know if it is still not working

**Comment by deennoo** [comment]
Just test with the last lib you're asking + arduino ide 1.6.8 + esp8266com 2.1.0 release and get this error : 

FSBrowser.h no such file or directory.

Looking on ESP8266com v2.0.0 or v2.1.0 & v1.6.5 there is no file with this name

**Comment by sticilface** [comment]
That would be correct, it is a lib that I've made that is not public, however, it is removed from the latest git. 
https://github.com/sticilface/Melvanimate/blob/master/examples/Melvanimate-example/Melvanimate-example.ino#L9

so i would pull melvanimate again and see if it persists.

**Comment by deennoo** [comment]
ok done and works  for me on a Wemos Mini D1

**Comment by sticilface** [comment]
excellant

**Comment by deennoo** [comment]
Now have to find a way to use it on my home automation systeme (Domoticz)

Join us on ESPEasy : http://www.esp8266.nu/forum/viewtopic.php?f=6&t=300 !

**Comment by jpontius** [comment]
I'm still getting errors.  

```
In file included from /home/justin/Arduino/libraries/Melvanimate/src/helperfunc.h:7:0,
                 from /home/justin/Arduino/libraries/Melvanimate/src/Melvanimate.h:12,
                 from /tmp/arduino_d7fdb1fc18d97178355f301d0fc095b2/Melvanimate-example.ino:27:
/home/justin/Arduino/libraries/Melvanimate/src/mybus.h:3:25: fatal error: NeopixelBus.h: No such file or directory
 #include "NeopixelBus.h"
                         ^
compilation terminated.
exit status 1
Error compiling.
```

Is `#include "NeopixelBus.h"`  misspelled?

**Comment by jpontius** [comment]
Okay,  renamed `NeopixelBus.h` to `NeoPixelBus.h`  and I found another one 
`#include "melvtrix.h"` should be `#include "Melvtrix.h"`
I also found these needed to renamed.  I'm using linux,  case matters.

```
ArduinoJson.h
Melvtrix.h
Palette.h

```

**Comment by sticilface** [comment]
Ah good spot.  unfortunately I'm only able to use a mac, so i can't test this, and it doesn't throw an error...

**Comment by sticilface** [comment]
I've just pushed some fixes for that.  Can you let me know if it works?

**Comment by jpontius** [comment]
Just tried the latest example.  Looks like a file is missing.

```
In file included from /home/justin/Arduino/libraries/Melvanimate/examples/Melvanimate-example/Melvanimate-example.ino:22:0:
/home/justin/Arduino/libraries/Melvanimate/src/Melvanimate.h:13:16: fatal error: EQ.h: No such file or directory
 #include "EQ.h"
```

**Comment by jpontius** [comment]
Commenting out `EQ.h` I was able to get a little farther.  Now i'm getting: 

```
Build options changed, rebuilding all
/tmp/arduino_d7fdb1fc18d97178355f301d0fc095b2/Melvanimate-example.ino: In function 'void setup()':
Melvanimate-example:88: error: 'offFn' was not declared in this scope
   lights.Add("Off",          new SwitchEffect( offFn), true);        //  **  Last true indicates this is the default effect... ie... off...
                                                ^
Melvanimate-example:89: error: 'SimpleColorFn' was not declared in this scope
   lights.Add("SimpleColor",  new SimpleEffect(SimpleColorFn));       
                                               ^
exit status 1
'offFn' was not declared in this scope
```

**Comment by sticilface** [comment]
mmm....  removing the EQ.h (which i've pushed) seems to compile fine for me!  

The Error that you've got is kind of familiar though.  I had it once with a particular version of the arduino IDE that required forward declarations of all the functions, used.  Try putting this:

```
void offFn(effectState &state, EffectHandler* ptr);
void SimpleColorFn(effectState &state, EffectHandler* ptr);
```

just before the setup function?

**Comment by sticilface** [comment]
I've been battling with Travis and git all evening.  Hopefully, got it working now, so these inconsistencies can be highlighted much earlier, with Travis build failing!  Seems to work!

**Comment by jpontius** [comment]
SWEET!  It finally compiled with 

```
void offFn(effectState &state, EffectHandler* ptr);
void SimpleColorFn(effectState &state, EffectHandler* ptr);
```

inserted before the add effects line.

**Comment by sticilface** [comment]
cool...  

What version of the arduino IDE are you using?

**Comment by jpontius** [comment]
I'm on 1.6.7.  Unfortunately I'm having another problem.  It compiled and loaded okay on my 12e, but shows an error when going to the ip adress `Not found: /`

Serial console:

```
..
WiFi connected
IP address: 
192.168.0.108
Free Heap: 35712
Ready
```

**Comment by sticilface** [comment]
That would imply that you do not have the two files, but mainly the index.htm file located in the example data folder in SPIFFS on the ESP.  You need to hit dataupload in the tools menu of the IDE, (or install it if you do not have it)

**Comment by jpontius** [comment]
Awesome!  I had no idea about the spiffs upload thing.  It's working perfectly!

**Comment by sticilface** [comment]
excellent.  at some point i might add a lib, or functions from another lib that can automatically download these files to spiffs... so you just have to press a button and it will do it.  I already have that for another lib..
