### ISSUE TITLE
[not a issue] RGB to BRG

### ISSUE THREAD

**Issue by reaper7** [sticilface/Melvanimate#13]
Example works ok for me but I have
reversed colors when I try "SIMPLE COLOR"
I have different type of leds...WS2811
Is there any way to change default RGB to BRG?
because when I set 255,0,0 then I have blue light,
0,0,255 give me green, and 0,255,0 give me red light

**Comment by sticilface** [comment]
Yes, that is easy. Unfortunately it is not definable in the sketch.  The reason is that neopixelbus went template style recently to save on compiled space.  This means that all my references to neopixelbus have to be templates appropriately.  
https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object#neogrbfeature
although it is not listed there, there is a NeoBrgFeature which is hopefully what you need. 

There is a file in the Melvanimate directory called mybus.h containing the typedef. 

```
typedef NeoPixelBus<NeoGrbFeature, NeoEsp8266Uart800KbpsMethod> MyPixelBus;
```

This is where you have to change you implementation to whatever you have... 
I believe you will need

```
typedef NeoPixelBus< NeoBrgFeature, NeoEsp8266Uart800KbpsMethod> MyPixelBus;
```

Let me know if that works.

**Comment by reaper7** [comment]
not work as expected :(

so...

I try NeoPixelBus example for test (as console message show, led strip must give RGBW )
NeoGrbFeature give me BRGW  (g and b swapped)
NeoRgbFeature give me RBGW (g and b swapped)
NeoBrgFeature give me BGRW (g and r swapped)

**Comment by sticilface** [comment]
OK, in that case.  Next step.. 

Can you get the neopixelbus examples to work as expected? 
Not using my lib at all, just the example sketches.

**Comment by reaper7** [comment]
In my previous message (above) I wrote about example from neopixelbus library (example: NeoPixelTest)

**Comment by sticilface** [comment]
Now I'm a bit confused. 

What type of LEDs are you using.  3 colour or 4colour.

If you are using the four colour R + G + B + W then you need to use the corresponding colour feature for 4 colour LEDs...  does that make sense.. (I think, but i can't test.)  this is a neopixelbus issue though... 

maybe try

NeoBrgwFeature ?

**Comment by reaper7** [comment]
no, this is ws2811 controler with RGB leds only (without additional white led).
Example from neopixelbus->NeoPixelTest sets colors on the LEDs strip in order: 
1led in strtip->R, 2led in strip->G, 3led in strip->B, 4led in strip->W
https://github.com/Makuna/NeoPixelBus/blob/master/examples/NeoPixelTest/NeoPixelTest.ino#L84

but as I wrote above, when I try to set different type, then my result is wrong in any case:
NeoGrbFeature give me 1led=B 2led=R 3led=G 4led=W (g and b swapped)
NeoRgbFeature give me 1led=R 2led=B 3led=G 4led=W (g and b swapped)
NeoBrgFeature give me 1led=B 2led=G 3led=R 4led=W (g and r swapped)

**Comment by sticilface** [comment]
I've had a look at the test sketch, I've had a look at the neopixel bus code, but i can't see any reason why this would happen..  

I'm going to suggest an issue on neopixelbus now, as I'm out of options

**Comment by reaper7** [comment]
my LEDs are looks like those:
http://g01.a.alicdn.com/kf/HTB1BIXeIXXXXXc2XpXXq6xXFXXXW/20-pcs-21mm-3-leds-WS2811-IC-5050-RGB-SMD-LED-Chip-Round-Bare-Board-with.jpg

maybe a neopixel issue or modules with wrong internal connections :D

**Comment by reaper7** [comment]
solved by adding additional future NeoRbgFeature to Makuna/Neopixelbus
