### ISSUE TITLE
Edit.htm.gz is a link to dropbox file not contained within code itself

### ISSUE THREAD

**Issue by jpfy** [sticilface/Melvanimate#14]
What should be in the Edit.htm.gz file?  I am trying out your example code but cannot compile as this file is a link 
Thank you

**Comment by sticilface** [comment]
Thought I'd got rid of those. Will remove it.  It's not needed for the example though

**Comment by sticilface** [comment]
Shouldn't stop u compiling or does it stop the spiffs image? 

You can delete it!

**Comment by jpfy** [comment]
Thank you will give it a go.

**Comment by jpfy** [comment]
Removing the alias worked a treat thanks
