### ISSUE TITLE
Turn of Access point

### ISSUE THREAD

**Issue by jpfy** [sticilface/Melvanimate#17]
Currently my device works well and is logged onto my home network.  However it is still broadcasting as an access point. Is there a way to turn this off.

**Comment by sticilface** [comment]
I'm guessing that you are using it with ESPManager?  is that correct?

**Comment by sticilface** [comment]
if you are, then i'm going to be releasing a newer much improved version of the ESPManager soon that should fix these AP issues once and for all...

**Comment by jpfy** [comment]
Thank you.

**Comment by sticilface** [comment]
have you tired the latest ESPmanager..... it should fix that

**Comment by jpfy** [comment]
Not yet but will be trying it this Weekend

**Comment by jpfy** [comment]
Thank you
