### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by labomat** [sticilface/Melvanimate#18]
I got the following error compiling:

```
In file included from C:\Users\lab\Documents\Arduino\libraries\Melvanimate-master\src/EQ.h:16:0,
                 from C:\Users\lab\Documents\Arduino\libraries\Melvanimate-master\src/Melvanimate.h:13,
                 from Melvanimate-example.ino:22:
C:\Users\lab\Documents\Arduino\libraries\Melvanimate-master\src/PropertyManager.h: In member function 'virtual bool Variable<IPAddress>::parseJsonProperty(ArduinoJson::JsonObject&)':
C:\Users\lab\Documents\Arduino\libraries\Melvanimate-master\src/PropertyManager.h:298:14: error: 'class IPAddress' has no member named 'fromString'
     if (temp.fromString(input)) {
```

**Comment by sticilface** [comment]
What version of the arduino IDE are you using.
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/IPAddress.h#L51

it should be in the core. 

https://github.com/esp8266/Arduino/commit/c1e91c722f1378bf7b1519a4931fc224c7d1112e

**Comment by labomat** [comment]
I use version 1.6.5. Will try 1.6.10.

**Comment by sticilface** [comment]
oh sorry.. i meant the ESP8266?

**Comment by sticilface** [comment]
https://github.com/esp8266/Arduino

**Comment by labomat** [comment]
OK, I installed 1.6.10 (had to re-install boards and some libraries) but now it is compiling and running (at least the web page - no led output at the moment).
Thanks!
