### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by wutu** [sticilface/Melvanimate#2]
Hi sticilface,
I can not compile the project. I use Arduino IDE 1.6.8, ESP8266 2.1.0 stable, PubsubClient 1.9.1.
I had this error:

```
In file included from C:\Users\wutu\Documents\Arduino\libraries\Melvanimate\src/Melvanimate.h:20:0,

                 from C:\Users\wutu\AppData\Local\Temp\arduino_modified_sketch_607679\Melvanimate-example.ino:24:

C:\Users\wutu\Documents\Arduino\libraries\Melvanimate\src/MelvanimateMQTT.h: In constructor 'MelvanimateMQTT::MelvanimateMQTT(Melvanimate*, IPAddress, uint16_t)':

C:\Users\wutu\Documents\Arduino\libraries\Melvanimate\src/MelvanimateMQTT.h:29:11: error: 'class PubSubClient' has no member named 'setClient'

   _client.setClient(_espClient);

           ^

C:\Users\wutu\Documents\Arduino\libraries\Melvanimate\src/MelvanimateMQTT.h:30:11: error: 'class PubSubClient' has no member named 'setServer'

   _client.setServer(Addr, Port);

           ^

C:\Users\wutu\Documents\Arduino\libraries\Melvanimate\src/MelvanimateMQTT.h:31:11: error: 'class PubSubClient' has no member named 'setCallback'

   _client.setCallback(  std::bind (&MelvanimateMQTT::_handle, this, _1, _2, _3));

           ^

C:\Users\wutu\AppData\Local\Temp\arduino_modified_sketch_607679\EffectCallbacks.ino: In function 'void setup()':

EffectCallbacks:141: error: 'class ESPmanager' has no member named 'deviceName'

         float progress;

                              ^
```

I know that the project is at an early stage and understand if you refuse to solve this ;)

**Comment by sticilface** [comment]
Looking at this error

```
 'class PubSubClient' has no member named 'setClient'
```

it looks like you might not have this lib
https://github.com/knolleary/pubsubclient

which contains setClient
https://github.com/knolleary/pubsubclient/blob/master/src/PubSubClient.h#L122

Do you have this lib?
have you included it?

**Comment by wutu** [comment]
Thank you for answer.
Sure. As I write above Pubsubclient 1.9.1.
Now I tried 2.6.0. Unfortunately again with another error.
With what version you compile it?

**Comment by sticilface** [comment]
latest git. 
what's you're latest error?
I usually run the latest staging for all my stuff... need more info I'm afraid... 
As you mentioned this lib... is kind of bleeding edge...

**Comment by sticilface** [comment]
pushed a big update.. not sure if that changes things?

**Comment by wutu** [comment]
I used git version libraries PubsubClient, NeoPixelBus. And with the last update from you, I successfully compiled.
I fear that it is to me still too developmental stage. :)
ESP Manager working. (nice project btw)
But do not connect to the Broker and so on.

**Comment by sticilface** [comment]
I've just pushed a load of changes as well as some documentation, and a much cleaner example
Please explain more by 'do not connect to Broker' ?

**Comment by wutu** [comment]
Many thanks for README. I did not know that I can record directly to SPIFFS. :)
I just had to lower port speed to 115200.
Everything works well. Now I am playing with MQTT. On the weekend will hopefully have more time. I will try create some animation. Matrix is on the way from China.
Thanks so much for this excellent project.
