### ISSUE TITLE
Hardware question

### ISSUE THREAD

**Issue by tcprst** [sticilface/Melvanimate#23]
Hello @sticilface! 

First I must commend you for your great work on this project, great job!

I just had a quick question as to which specific level shifter do you use to interface between your ESP8266 chip at 3.3v logic level to the LED strip which operates at 5v?  I was wondering if you had experience with one in particular that worked very well or if you did something else entirely different.

Thank you and best regards,
tcprst

**Comment by tcprst** [comment]
Actually, I just happened to read through the issue regarding adding microphone support (#10) and in there I found the logic level converter you use!  Sorry for opening this needless GitHub issue.

For anyone else who finds this later or is wondering (maybe @sticilface can add this to his README.md):

https://github.com/sticilface/Melvanimate/issues/10

The logic level converter is a 74HCT245N

As sticilface said:

> It's A logic level converter. 
> That changes the esp 3.3V to 5V. 
> Not found a smaller one that works, and this works perfectly so I've carried on using it.

**Comment by sticilface** [comment]
No problem.  I've been looking desperately for a smd smaller version of something that will work, but nothing seems to do the job as well. 

paul s. from teensy wrote a forum entry on why... and he is the man who knows
https://www.pjrc.com/teensy/td_libs_OctoWS2811.html
https://forum.pjrc.com/threads/25549-What-is-the-difference-between-the-74HCT245-and-sparkfun-s-logic-level-converter
