### ISSUE TITLE
cannot compile wemos d1

### ISSUE THREAD

**Issue by rwrw01** [sticilface/Melvanimate#26]
have tried a lot of library function but keep getting compiling errors:

`
C:\Users...\Documents\Arduino\libraries\Melvanimate\src\MelvanimateMQTT.cpp:31:10: note: candidate is:

In file included from C:\Users...\Documents\Arduino\libraries\async-mqtt-client\src/AsyncMqttClient.h:4:0,

```
             from C:\Users\...\Documents\Arduino\libraries\Melvanimate\src\MelvanimateMQTT.h:4,

             from C:\Users\...\Documents\Arduino\libraries\Melvanimate\src\MelvanimateMQTT.cpp:4:
```

C:\Users...\Documents\Arduino\libraries\async-mqtt-client\src/AsyncMqttClient.hpp:43:20: note: AsyncMqttClient& AsyncMqttClient::onConnect(AsyncMqttClientInternals::OnConnectUserCallback)

   AsyncMqttClient& onConnect(AsyncMqttClientInternals::OnConnectUserCallback callback);

```
                ^
```

C:\Users...\Documents\Arduino\libraries\async-mqtt-client\src/AsyncMqttClient.hpp:43:20: note:   no known conversion for argument 1 from 'MelvanimateMQTT::MelvanimateMQTT(Melvanimate*, IPAddress, uint16_t)::__lambda0' to 'AsyncMqttClientInternals::OnConnectUserCallback {aka std::function<void(bool)>}'

exit status 1`

**Comment by sticilface** [comment]
This might be due to the fact that the asyncMQTT lib changed is signature for the message callback a while back.  

Can you make sure you are using latest versions of both!

**Comment by sticilface** [comment]
OK found it.  the signature of the Cb had changed again.  should be fixed now
