### ISSUE TITLE
ESP-01 WS2812 not lighting up

### ISSUE THREAD

**Issue by drschnalli** [sticilface/Melvanimate#27]
Hello, im using a ESP8266-01 (8-pins variant) but i cannot light up my ws2812 leds.  I have read that i must use the gpio2 method (uart-driven?!). But i never found a way to change.. and i dont know to change which files.

**Comment by sticilface** [comment]
Hi.  

try placing 

```
#define WS2812_UART_METHOD
```

before you include melvanimate.h

That should work for GPIO2 on ESP01.

**Comment by drschnalli** [comment]
Does not work for me. :(

When compiling it says:

C:\Program Files (x86)\Arduino\libraries\Melvanimate-master\src/mybus.h:37:39: note: #pragma message: WS2812_UART_METHOD

   #pragma message("WS2812_UART_METHOD")

I set the ESP8266-01 via Arduino 1.6.9 to 160mhz.... dont know if that works or not. I saw that my esp is rebooting sometimes when im trying to connect gpio do DIN of my WS2812 Pixelstrip  

I think im gonna give up and wait for my nocemdu to arrive.

**Comment by sticilface** [comment]
you are right.  i tried this and although you get the message that it is using UART it does not.  

uncomment this line in the lib

https://github.com/sticilface/Melvanimate/blob/master/src/mybus.h#L15

unfortunately global defines in the ino don't work from the sketch.  it works great with platformio.  this method became essential when neopixelbus became templated unfortunately..

**Comment by drschnalli** [comment]
The mybus file is the one i found #define WS2812_UART_METHOD first... i uncommented it and tried out and after that i opened that issue. And it gave me the same pragma message (i think its just for debug?)

But when i tested this i was using the 80mhz option and nothing on my led strip happened. Maybe it will work then ?

**Comment by sticilface** [comment]
the thing to try in that case is to see if you can drive the LEDs using the neopixel bus examples.  

Get that to work first, then let me know.  I use both versions and rugby leds all over the house, so the sketch definitely works.  this might be an issue with the level conversion, as theoretically you need to use a 3.3 to 5v level shifter....

**Comment by drschnalli** [comment]
I already got esp8266_tpm2net on my esp01 working with the same wiring. thats why im wondering about this so much. But in approx 1-2 weeks the nodemcu's will arrive and i will give them a test. Do they also need a level converter? I think it also used the UART Output

Do you have an neopixel example i can directly run on my esp01? (sorry im not that pro atm, i hope i get trough this:D )

**Comment by sticilface** [comment]
curious.  If you can get the examples from neopixelbus to work then that would be the best thing, can you humour me and just see if you can get it to work

**Comment by sticilface** [comment]
any progress?  feel free to reopen if not
